#:schema node_modules/wrangler/config-schema.json
name = "nest-notifier"
main = "src/index.ts"
compatibility_date = "2024-10-11"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true


[vars]
AIRTABLE_BASE_ID = "appaQHwFrRnN00W0A"
AIRTABLE_TABLE_NAME = "Organisations"
